### ISSUE TITLE
Gaussian prior in the implementation

### ISSUE THREAD

**Issue by YifuTao** [BayesRays/BayesRays#19]
Hi @lilygoli, thank you for your great work!

May I follow up on your explanation of equation (10) in #4 

> thus, it makes sense to place a regularizing independent Gaussian prior θ ∼ N (0, λ−1) on our new parameters and formulating the posterior p(θ|I) whose negative loglikelihood h(θ) is given by

In the implementation, is the second term $λ∥θ∥^2$ used? I couldn't find it, and don't quite understand the need for this Gaussian prior regularisation in eq.10. I understand that zero is the mode as NeRF is assumed to be in the local minima, but how you goes to the Gaussian prior from that and what's the benefit?

**Comment by papercv7** [comment]
Hi!
yes, the second order derivative of $\lambda \|\theta\|^2$ is just $\lambda I$ which is added to the Hessian [here](https://github.com/BayesRays/BayesRays/blob/edd549e323654c26d52797e43ef17de842befeef/bayesrays/scripts/output_uncertainty.py#L38).

The reason for it can be explained both theoretically and practically:
1- theoretically: We are looking for a posterior on our parameters $\theta$, so we need to have a prior that is then updated with the likelihood through the Bayes rule. We assume standard Gaussian prior as a common and easy prior to work with. Maybe the connection of the sentence you quoted with its previous sentence is a bit vague, as we intended to refer to the **zero-mean** Gaussian being the prior, with the **zero** mean coming from the NeRF being in a local minima already.
2- practically: In practice if you don't have that regularizing factor of $\lambda$ you can face situations where your hessian value is zero and hence the uncertainty (inverse hessian) is undefined/infinity. Therefore, the regularizer helps prevent that.

**Comment by lilygoli** [comment]
Hi!
yes, the second order derivative of $\lambda \|\theta\|^2$ is just $\lambda I$ which is added to the Hessian [here](https://github.com/BayesRays/BayesRays/blob/edd549e323654c26d52797e43ef17de842befeef/bayesrays/scripts/output_uncertainty.py#L38).

The reason for it can be explained both theoretically and practically:
1- theoretically: We are looking for a posterior on our parameters $\theta$, so we need to have a prior that is then updated with the likelihood through the Bayes rule. We assume standard Gaussian prior as a common and easy prior to work with. Maybe the connection of the sentence you quoted with its previous sentence is a bit vague. We intended to refer to the **zero-mean** Gaussian being the prior, with the **zero** mean coming from the NeRF being in a local minima already.
2- practically: In practice if you don't have that regularizing factor of $\lambda$ you can face situations where your hessian value is zero and hence the uncertainty (inverse hessian) is undefined/infinity. Therefore, the regularizer helps prevent that.

**Comment by YifuTao** [comment]
Thank you so much for your response!
