### ISSUE TITLE
Dataset download and camera_path format

### ISSUE THREAD

**Issue by AuthorityWang** [BayesRays/BayesRays#2]
Hi, the [link](https://drive.google.com/file/d/1XbK5RAuYKsCG4Ub_YhwPxG7eSH_0MqP6/view?usp=sharing) of a dataset of Loader Truck scene gave me the error of the file does not exist, could you fix this? By the way, I wonder about the format of the camera_path_filename mentioned in the render uncertainty command 
`ns-render-u camera-path --load-config={PATH_TO_CONFIG} --unc_path {PATH_TO_UNCERTAINTY} --output-path {PATH_TO_VIDEO} --downscale-factor 2  --rendered_output_names rgb depth uncertainty  --filter-out True --filter-thresh 1. --white-bg True --black-bg False  --camera_path_filename {PATH_TO_CAMERA_PATH}` ? Thanks.

**Comment by lilygoli** [comment]
Thanks for reporting this! The link should be fixed now.
The path should be the path to the `.json` file. A sample camera path exists in the linked zip file.
