### ISSUE TITLE
Approxiamted Hessian Computation - why adding before squaring?

### ISSUE THREAD

**Issue by YifuTao** [BayesRays/BayesRays#20]
Hi @lilygoli, may I ask a question regarding the hessian computation:

Given that the Hessian is approximated as Jacobian $H = J^T J$ and the covariance of parameter $\theta$ approximated with just the diagonal of the Hessian, each parameter $\theta_i$'s variance is $\frac{1}{N} (\partial \epsilon_1/\partial \theta_i)^2 + (\partial \epsilon_2/\partial \theta_i)^2 + ... + (\partial \epsilon_n/\partial \theta_i)^2$ where $\epsilon$ is the L2 loss of the rendered colour, and each term here is a separate observation. They are summed **after** being squared.

However, in https://github.com/BayesRays/BayesRays/blob/main/bayesrays/scripts/uncertainty.py#L71
```
# all_r is the gradient weighted by voxel interplation weight
grad_r_1 = torch.bincount(inds_all, weights=all_r[...,0]) #for first element of deformation field
grad_1 = grad_r_1**2+grad_g_1**2+grad_b_1**2
```
Consider two samples along a ray that intersect with the same voxels, which means they have the same ray index (from `dmy`) and the same voxel index (from `inds`) as in `keys_all`. With the current implementation, they will be summed first with `torch.bincount` with weights, **before** being squared, i.e. $(\partial \epsilon_1/\partial \theta_i + \partial \epsilon_2/\partial \theta_i)^2$.

Could you explain the consideration behind this as opposed to square the gradients first?

**Comment by YifuTao** [comment]
Actually I think the implementation should indeed sum up the gradient for each sample along a ray, since them combined leads to the observation of each ray, rather than each sample is one observation.

**Comment by lilygoli** [comment]
yes the contribution of the samples along a ray to each grid cell should be combined first and then squared

**Comment by YifuTao** [comment]
Thank you for your reply! Closing the issue
