### ISSUE TITLE
Why use a deformation field when the offsets returned are all zero?

### ISSUE THREAD

**Issue by damian-bowness** [BayesRays/BayesRays#23]
Hi,

Thank you for sharing your work, it's very interesting! I've been playing around with it to gain a better understanding and I've noticed that the offsets from the deformation field are all zero and yet I can still produce an uncertainty field.  In fact, I've replaced the offsets from the deformation field with a tensor of zeros and produced a very similar uncertainty field.  As an additional experiment, I set the offsets with torch.randn which produced a different uncertainty field.   I'm wondering why we are able to measure uncertainty when the offsets are zero?

Below is a table displaying stats on the Hessian values produced from the different sets of offsets.  These values were generated with the default poster dataset from Nerfstudio:

![table_of_hessian_stats_from_offsets](https://github.com/user-attachments/assets/d46f78cc-5aa7-465d-88fc-e7d949d9de5b)

Below are captures of the uncertainty rendering starting with offsets generated from the deformation field, then offsets as a tensor of zeros, and then finally offsets from randn:

![uncertainty_render_deform_field_offsets](https://github.com/user-attachments/assets/541a59ad-21c0-49a3-a639-40fe7b0886d3)
![uncertainty_render_zero_offsets](https://github.com/user-attachments/assets/c49db277-98ef-4d64-86ef-2824852b1544)
![uncertainty_render_randn_offsets](https://github.com/user-attachments/assets/05664129-a438-4970-8cd2-84b4093ac283)

**Comment by lilygoli** [comment]
Hi, yes we set the deformation to zero as discussed in section 4.2 of the paper, please take a look at #14 and #4 for more explanation on this.

**Comment by damian-bowness** [comment]
Hi, thank you for your response! One final question, why use a HashEncoding object to set the offsets instead of a tensor of zeros? e.g.` offsets = torch.zeros_like(pos) `

**Comment by lilygoli** [comment]
It should be the same, the choice of a hashgrid is to make the code consistent with iNGP code. I think the hashgrid also has nice utility functions for querying points etc.

**Comment by damian-bowness** [comment]
Ok, great! Thank you for taking the time to get back to me, I appreciate it! I apologize for not finding the answers you've previously given to others.
