### ISSUE TITLE
iNGP implementation

### ISSUE THREAD

**Issue by rlit** [BayesRays/BayesRays#3]
Amazing work, thanks!

In figure 3 of the paper it is implied that you tired this in [instant-NGP](https://github.com/NVlabs/instant-ngp). If so, would you mind sharing how can this be done easily? 
Or even the script you used?

**Comment by lilygoli** [comment]
Hi,

Yes, the uncertainty-related functionalities are currently implemented for Nerfacto, iNGP and mip-nerf models of nerfstudio. For example [here](https://github.com/BayesRays/BayesRays/blob/b8f986ce079c74551015b8aec744758d4813b13f/bayesrays/scripts/uncertainty.py#L151) you can see the impelementation of uncertainty extraction function for iNGP. 
To run BayesRays for iNGP or mip-NeRF models you do not need to change anything, train your iNGP model with nerfstudio and then run BayesRays normally, the code itself will detect the underlying architecture (nerfacto ,iNGP, mip-nerf).

**Comment by rlit** [comment]
Thanks,
Just to be clear, I meant the original iNGP implementation (from NV labs)

**Comment by lilygoli** [comment]
no we only have implemented the method on different nerfs architectures in nerfstudio. 
If you want to transfer the method to another codebase, the main bit is uncertainty extraction in `uncertainty.py`. The rest (for example rendering) can be added to their original methods with a few lines of code.
