### ISSUE TITLE
Questions regarding the implementation

### ISSUE THREAD

**Issue by hubert0527** [BayesRays/BayesRays#4]
Dear authors,

I am a bit confused with the implementation, and thus seeking for your clarification. Your help is greatly appreciated!

In Section 4.2 of the paper mentioned:
> We can now reparametrize the radiance field R with θ by perturbing each coordinate x before applying the already optimized NeRF neural network.

I understand this as a random small perturbation is applied to each x. However, the implementation in this codebase [initialized the hash table to be a zero tensor](https://github.com/BayesRays/BayesRays/blob/b8f986ce079c74551015b8aec744758d4813b13f/bayesrays/scripts/uncertainty.py#L305), so any query to this hash table should result in a zero value (i.e., zero `offsets` to deformation). Thus, the applying deformation with `frustums.set_offsets` does not introduce any perturbations. 

The codes seem to be equivalent to setting `offsets = torch.zeros_like(pos)`. I ran the codes with this line replacing `self.deform_field(pos)`, and I indeed don't see perceptible differences.

Could you help clarify the rationale here and if I misunderstood anything?
Sincerely thanks!

**Comment by lilygoli** [comment]
I'm gonna close this issue as there seems to be no follow-up questions, but feel free to re-open it if something comes up!

**Comment by YifuTao** [comment]
Hi @lilygoli, thank you for your response! 

May I follow up on your explanation of equation (10)

>thus, it makes sense to place a regularizing independent Gaussian prior θ ∼ N (0, λ−1) on our new parameters and formulating the posterior p(θ|I) whose negative loglikelihood h(θ) is given by
 $$h(θ) = EnEr∼In ∥ Cθ(r) − Cgt n (r)∥^2_2 + λ∥θ∥^2 . (10)$$

In the implementation, is the second term $λ∥θ∥^2$ used? I couldn't find it, and don't quite understand the need for this Gaussian prior regularisation in eq.10. I understand that zero is the mode as NeRF is assumed to be in the local minima, but how you goes to the Gaussian prior from that and what's the benefit?
