### ISSUE TITLE
How is the variance of Gaussian calculated in the paper?

### ISSUE THREAD

**Issue by lishaobingdong** [BayesRays/BayesRays#5]
![06e1b6acb94af965b2b071f92c5cf66](https://github.com/BayesRays/BayesRays/assets/92428242/c779f712-6fd1-403f-b0a0-4b4e69b9aaf2)
Hello! Thank you for your excellent work! 
I have a question about this gaussian, how is the variance 0.5 calculated? According to section 3.2, shouldn't it be calculated using the second derivative?

**Comment by lilygoli** [comment]
Hi!

Take note p(C|\phi) is the _likelihood_ of the predicted color given network parameters. When mean squared error is used in optimization that is equivalent to maximizing likelihood if the ground truth color came from a normal distribution centered at predicted color and variance equal to a constant (0.5 just leads to a nicer final derivation, the choice of this constant does not affect the minimization objective). There is a good explanation at the beginning of [this blog post](of this in the beginning) from David Duvenaud about BNNs. 

Now in 3.2 we are looking at another probability distribution and that is the _posterior_ probability distibution of the deformation parameters conditional on the training data samples and network parameters.

**Comment by lishaobingdong** [comment]
Thank you! 
I think I already understand. So 0.5 is just chosen for convience, and it just affects a coefficient in eq.19.

**Comment by chenwydj** [comment]
<img width="509" alt="image" src="https://github.com/BayesRays/BayesRays/assets/10953233/986f1f2b-1879-4778-9866-beb71a7730bd">

@lilygoli May I have a follow-up question? I am confused about this part.

Are you claiming that the minimum of Eq.10 is achieved when all network parameters are 0? Why does the red squiggly line hold (i.e. the volume rendering achieves the best MSE error hen all network parameters are 0)?

Thank you very much!

**Comment by lilygoli** [comment]
$\theta$ is not representing the network parameters, $\theta$ is representing the deformation parameters of the deformation grid. $\phi$ is representing nerf's network parameters and $\phi^{\*}$ is the optimized network parameters (remember we get as input an already optimized and trained NeRF so $\phi^*$ is known.
We are claiming since the **network parameters** are already optimized ($\phi ^ *$), a zero deformation grid ($\theta=0$) achieves minimum for equation 10.

**Comment by chenwydj** [comment]
Thanks @lilygoli !
