### ISSUE TITLE
How to try with my own data

### ISSUE THREAD

**Issue by ToEndeavor** [BayesRays/BayesRays#6]
This is a very good piece of work. I would like to ask if you have tried conducting experiments with your own data, or if you have used a limited number of perspectives to generate uncertainty?And How can I try this work with my own data.
Looking forward to your reply.

**Comment by lilygoli** [comment]
Hi!

Yes I have tried my own data, in fact the teaser figure of the bulldozer is a nerfacto model trained from a video I got of a bulldozer. If there are limited views, short video, or more occlusion you will most probably see more floaters in your NeRF and can use Bayes' Rays on it to remove the floaters. 
For working with your own data, you can simply take a video, and follow [Nerfstudio's instruction](https://docs.nerf.studio/quickstart/custom_dataset.html) to train a NeRF (nerfacto model recommended). Then follow the instructions for uncertainty extraction and rendering in the main page of this repository.

**Comment by ToEndeavor** [comment]
Yes, I understand that providing too few images will result in my NeRF with more floaters. However, I want to experiment with a limitted number of images (around 5) to see if it's possible to compute uncertainty. If your works similarly to NerfStudio and allows for the use of custom data, I can try it out myself. Thank you so much for your response.

**Comment by lilygoli** [comment]
Yeah sure you can try it out. We have some eperiments with 5-10 views too on the LF dataset, you can also check those out if it helps.
